### ISSUE TITLE
Add external dataset

### ISSUE THREAD

**Issue by jeslev** [Georgetown-IR-Lab/OpenNIR#22]
Hello, 
I'm testing the pipeline and I wonder if it is possible to add external datasets (indexed with Anserini) into the code? And if it is possible, is there a guide or tutorial on how to do it? The same question if I want to add a new model (ranker)

Thanks

**Comment by seanmacavaney** [comment]
Hi @jeslev,

**Datasets**

There are currently two approaches for adding datasets. You can either use the "flex" dataset and point it to a particular TSV file containing queries and documents, or create a new dataset class, which allows you to perform additional pre-processing and configurations (e.g., including different subsets of queries for different purposes).

To use the flex dataset, you can just run `scripts/init_dataset.sh dataset=flex dataset.subset=my_dataset`, and then follow the prompts. These will give you information about the required file format and so forth. You can then use it as a training, validation, or test dataset by setting `train_ds=flex train_ds.subset=my_dataset`, `valid_ds=flex valid_ds.subset=my_dataset` or `test_ds=flex test_ds.subset=my_dataset`.

If you want to make a new dataset class, you can follow an existing example from `onir/datasets/`. A relatively straightforward one is antique. Most of the code involves the initialization of the dataset (i.e., how to pre-process the queries, documents, and relevance judgments). Be sure to set `@datasets.register('my_dataset')`. You then need to import it in `onir/datasets/__init__.py` and you should be good to go. You'll be able to use it as a training, validation, or test dataset by setting `train_ds=my_dataset`, `valid_ds=my_dataset` or `test_ds=my_dataset`.

It sounds like it may be beneficial to add a third way, which would be to take an existing Anserini index and use that? This would only be feasible if the index was built using `-storeRaw` (or I guess `-storeContents`), because the original document text is consumed by the ranking models. Let me know if this would be a valuable feature to add. It may not be too much work to add because the Robust dataset already does something similar.

**Rankers**

Rankers are split into two parts-- the logic for building up the token representations (these are `vocab`s because they are the representations are linked directly to the lexicon, e.g., BERT's lexicon and tokenization logic is different than GloVe's). These representations are consumed by `ranker`s, which perform various operations to the representations to build a ranking score. For instance, KNRM performs kernel pooling over a query-document similarity matrix.

The process for adding a new ranker or vocab is similar to adding a dataset. There are plenty of examples in `onir/vocab` and `onir/rankers`. Once added, you can use them in a pipeline by setting `ranker=my_ranker` or `vocab=my_vocab`.

**Comment by jeslev** [comment]
Thanks for the quick answer! I'll check into that
